### ISSUE TITLE
Is it possible to only highlight(one color) the search result in current working buffer?

### ISSUE THREAD

**Issue by cyfyifanchen** [timakro/vim-searchant#13]
For example:
If I want to search `submit` in a file, after I run `/submit`, the results of searching `submit` are only showing in current working buffer.

**Comment by timakro** [comment]
This would be possible if the built-in search highlighting option wouldn't be used. Though the problem with custom highlighting is that it can't handle the `magic`, `ignorecase` and `smartcase` options, this is already the case for the current result highlighting, see #5, #6 and #7. I found no good way to support those options yet and I don't want to switch to custom highlighting with the drawback of loosing those options.

EDIT: Those issues could be fixed by parsing the search patterns in the script itself but I don't have time for implementing this right now. Also the search pattern should be stored in a window specific variable then.

**Comment by cyfyifanchen** [comment]
Thanks for the answer. I thought it might be a good feature to add on, however it doesn't seem to be that way.

**Comment by timakro** [comment]
Keep this issue open please, I consider this a bug. As I stated in the EDIT of my last comment it's definitely fixable I just won't do it in the near future.
