### ISSUE TITLE
Center search result in middle of screen

### ISSUE THREAD

**Issue by EdSplendor** [timakro/vim-searchant#8]
Hi,

could you add an option to center the search results while going through them?
I used this mappping in the past:
nnoremap n nzzzv
nnoremap N Nzzzv

but it gets disabled when I use your plugin.

Thanks
Ed

**Comment by timakro** [comment]
I don't know if there is a possibility to detect key presses while keeping the users mappings. I asked a [question about this on stackoverflow](http://stackoverflow.com/questions/37895456/map-key-to-itself-and-another-key-without-overwriting-the-previous-mapping-of-th). I will wait for a few days for someone to answer my question. Otherwise I will implement a setting to do exactly what you requested. Obviously keeping the users mappings would be way better.
